In [1]:
# print all the outputs in a cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import numpy as np

In [2]:
BB=pd.read_csv('baseball_stats.csv')
W=pd.read_csv('Denver_Weather.csv')
BB.replace('D',1.0, inplace=True)
BB.replace('N',0.0, inplace=True)

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (14,72) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
BB[BB.Home=='COL']

,Date,Day of Week,Visitor,Visitor Division,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,...,Home Earned Runs (Team),Home Wild Pitches,Home Balks,Home Outs,Home Assists,Home Errors,Home Passed Balls,Home Double Plays,Home Triple Plays,Acquisition Info
51,4/10/2009,Fri,PHI,NL,COL,NL,3,10,51,1.0,...,3,1,0,27,15,1,0,3,0,Y
66,4/11/2009,Sat,PHI,NL,COL,NL,8,4,54,0.0,...,8,0,0,27,6,0,0,0,0,Y
81,4/12/2009,Sun,PHI,NL,COL,NL,7,5,54,1.0,...,7,0,0,27,13,0,0,3,0,Y
229,4/24/2009,Fri,LAN,NL,COL,NL,6,5,54,0.0,...,6,1,0,27,12,0,0,2,0,Y
244,4/25/2009,Sat,LAN,NL,COL,NL,6,5,54,0.0,...,6,0,0,27,6,0,0,0,0,Y
259,4/26/2009,Sun,LAN,NL,COL,NL,4,10,51,1.0,...,4,0,0,27,9,1,0,1,0,Y
275,4/27/2009,Mon,SDN,NL,COL,NL,7,12,51,0.0,...,6,0,0,27,8,1,0,1,0,Y
288,4/28/2009,Tue,SDN,NL,COL,NL,4,3,54,0.0,...,4,0,0,27,14,1,0,0,0,Y
304,4/29/2009,Wed,SDN,NL,COL,NL,5,7,51,1.0,...,5,0,0,27,12,0,0,1,0,Y
396,5/6/2009,Wed,SFN,NL,COL,NL,1,11,51,0.0,...,1,1,0,27,10,0,0,1,0,Y
410,5/7/2009,Thu,SFN,NL,COL,NL,8,3,54,1.0,...,5,0,0,27,15,3,0,0,0,Y
426,5/8/2009,Fri,FLO,NL,COL,NL,8,3,54,0.0,...,8,1,0,27,12,0,0,0,0,Y
441,5/9/2009,Sat,FLO,NL,COL,NL,3,1,54,0.0,...,3,0,0,27,8,1,0,0,0,Y
456,5/10/2009,Sun,FLO,NL,COL,NL,2,3,51,1.0,...,1,0,0,27,15,1,0,0,0,Y
475,5/12/2009,Tue,HOU,NL,COL,NL,1,12,51,0.0,...,1,1,0,27,13,0,0,0,0,Y
490,5/13/2009,Wed,HOU,NL,COL,NL,15,11,54,0.0,...,15,0,0,27,8,0,0,0,0,Y
504,5/14/2009,Thu,HOU,NL,COL,NL,5,3,54,1.0,...,2,0,0,27,11,3,0,1,0,Y
659,5/25/2009,Mon,LAN,NL,COL,NL,16,6,54,1.0,...,16,1,0,27,10,1,0,0,0,Y
674,5/26/2009,Tue,LAN,NL,COL,NL,7,1,54,0.0,...,6,0,0,27,17,1,0,1,0,Y
689,5/27/2009,Wed,LAN,NL,COL,NL,8,6,54,1.0,...,7,0,0,27,17,1,0,3,0,Y
708,5/29/2009,Fri,SDN,NL,COL,NL,0,3,51,0.0,...,0,0,0,27,18,0,0,2,0,Y
724,5/30/2009,Sat,SDN,NL,COL,NL,7,8,53,0.0,...,6,1,0,27,11,1,0,1,0,Y
739,5/31/2009,Sun,SDN,NL,COL,NL,5,2,54,1.0,...,5,0,0,27,10,0,0,0,0,Y
900,6/12/2009,Fri,SEA,AL,COL,NL,4,6,51,0.0,...,4,0,0,27,17,0,0,2,0,Y
915,6/13/2009,Sat,SEA,AL,COL,NL,3,5,51,0.0,...,3,2,0,27,15,0,0,1,0,Y
930,6/14/2009,Sun,SEA,AL,COL,NL,1,7,51,1.0,...,1,0,0,27,9,0,0,1,0,Y
946,6/16/2009,Tue,TBA,AL,COL,NL,12,4,54,0.0,...,12,0,0,27,8,0,0,0,0,Y
961,6/17/2009,Wed,TBA,AL,COL,NL,3,5,51,0.0,...,3,0,0,27,15,2,0,1,0,Y
976,6/18/2009,Thu,TBA,AL,COL,NL,3,4,51,1.0,...,3,0,0,27,4,2,0,0,0,Y
989,6/19/2009,Fri,PIT,NL,COL,NL,3,7,51,0.0,...,3,0,0,27,19,0,0,0,0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23545,8/6/2018,Mon,PIT,NL,COL,NL,0,2,51,0.0,...,0,0,0,27,10,0,0,1,0,NaN
23555,8/7/2018,Tue,PIT,NL,COL,NL,10,2,54,0.0,...,10,0,0,27,11,1,0,0,0,NaN
23571,8/8/2018,Wed,PIT,NL,COL,NL,4,3,54,1.0,...,3,0,0,27,12,2,0,0,0,NaN
23584,8/9/2018,Thu,LAN,NL,COL,NL,8,5,54,0.0,...,8,1,0,27,7,1,0,0,0,NaN
23596,8/10/2018,Fri,LAN,NL,COL,NL,4,5,51,0.0,...,4,1,0,27,14,0,0,1,0,NaN
23611,8/11/2018,Sat,LAN,NL,COL,NL,2,3,53,0.0,...,2,0,0,27,10,0,0,1,0,NaN
23627,8/12/2018,Sun,LAN,NL,COL,NL,3,4,53,1.0,...,3,0,0,27,9,0,0,1,0,NaN
23745,8/21/2018,Tue,SDN,NL,COL,NL,4,3,54,0.0,...,4,0,0,27,7,1,1,0,0,NaN
23760,8/22/2018,Wed,SDN,NL,COL,NL,2,6,51,0.0,...,2,0,0,27,8,0,0,0,0,NaN
23775,8/23/2018,Thu,SDN,NL,COL,NL,3,4,53,1.0,...,2,0,0,27,14,1,0,2,0,NaN
23785,8/24/2018,Fri,SLN,NL,COL,NL,7,5,54,0.0,...,7,0,0,27,11,1,1,0,0,NaN
23800,8/25/2018,Sat,SLN,NL,COL,NL,1,9,51,0.0,...,1,1,0,27,9,0,0,1,0,NaN
23816,8/26/2018,Sun,SLN,NL,COL,NL,12,3,54,1.0,...,8,1,0,27,14,2,0,1,0,NaN
23922,9/3/2018,Mon,SFN,NL,COL,NL,8,9,51,1.0,...,8,1,0,27,8,2,0,0,0,NaN
23937,9/4/2018,Tue,SFN,NL,COL,NL,2,6,51,0.0,...,2,0,0,27,9,0,0,1,0,NaN
23951,9/5/2018,Wed,SFN,NL,COL,NL,3,5,51,0.0,...,3,0,0,27,8,0,0,1,0,NaN
23970,9/7/2018,Fri,LAN,NL,COL,NL,4,2,54,0.0,...,2,0,1,27,13,1,0,2,0,NaN
23984,9/8/2018,Sat,LAN,NL,COL,NL,2,4,51,0.0,...,2,0,0,27,9,0,0,1,0,NaN
24000,9/9/2018,Sun,LAN,NL,COL,NL,9,6,54,1.0,...,8,2,0,27,8,1,0,0,0,NaN
24013,9/10/2018,Mon,ARI,NL,COL,NL,2,13,51,0.0,...,1,0,0,27,10,1,0,1,0,NaN
24023,9/11/2018,Tue,ARI,NL,COL,NL,6,3,54,0.0,...,6,0,0,27,12,0,0,2,0,NaN
24039,9/12/2018,Wed,ARI,NL,COL,NL,4,5,52,0.0,...,4,0,0,27,8,0,0,1,0,NaN
24052,9/13/2018,Thu,ARI,NL,COL,NL,3,10,51,1.0,...,3,0,0,27,14,1,0,3,0,NaN
24202,9/24/2018,Mon,PHI,NL,COL,NL,1,10,51,0.0,...,1,0,0,27,12,0,0,2,0,NaN
24215,9/25/2018,Tue,PHI,NL,COL,NL,3,10,51,0.0,...,2,1,0,27,12,2,0,2,0,NaN
24229,9/26/2018,Wed,PHI,NL,COL,NL,0,14,51,0.0,...,0,0,0,27,11,1,0,1,0,NaN
24243,9/27/2018,Thu,PHI,NL,COL,NL,3,5,51,1.0,...,3,0,0,27,5,0,0,0,0,NaN
24251,9/28/2018,Fri,WAS,NL,COL,NL,2,5,51,0.0,...,2,0,0,27,9,0,0,1,0,NaN
24267,9/29/2018,Sat,WAS,NL,COL,NL,12,2,54,0.0,...,12,0,0,27,14,1,0,2,0,NaN
24283,9/30/2018,Sun,WAS,NL,COL,NL,0,12,51,1.0,...,0,0,0,27,12,0,0,3,0,NaN

In [4]:
COL=BB.loc[BB.Home=='COL']
list(COL.columns)
COL

['Date',
 'Day of Week',
 'Visitor',
 'Visitor Division',
 'Home',
 'Home Division',
 'Visitor Score',
 'Home Score',
 'Game Length (outs)',
 'Day or Night',
 'If Completed at Later Date',
 'Stadium ID',
 'Attendance',
 'Game Length (minutes)',
 'Visitor Runs (by inning)',
 'Home Runs (by inning)',
 'Visitor At-Bats',
 'Visitor Hits',
 'Visitor Doubles',
 'Visitor Triples',
 'Visitor Homeruns',
 'Visitor RBIs',
 'Visitor Sacrifice Hits',
 'Visitor Sacrifice Flies',
 'Visitor HBP',
 'Visitor Walks',
 'Visitor Walks (intentional)',
 'Visitor Strikeouts',
 'Visitor Stolen Bases',
 'Visitor Caught Stealing',
 'Visitor Ground into Double Play',
 'Visitor Awarded First (interference)',
 'Visitor Left on Base',
 'Visitor Pitchers Used',
 'Visitor Earned Runs (individual)',
 'Visitor Earned Runs (team)',
 'Visitor Wild Pitch',
 'Visitor Balks',
 'Visitor Outs',
 'Visitor Assists',
 'Visitor Errors',
 'Visitor Passed Balls',
 'Visitor Double Plays',
 'Visitor Triple Plays',
 'Home At-Bats',
 'Home Hits',
 'Home Doubles',
 'Home Triples',
 'Home Homeruns',
 'Home RBIs',
 'Home Sacrifice Hits',
 'Home Sacrifice Flies',
 'Home Hit by Pitch',
 'Home Walks',
 'Home Walks (intentional)',
 'Home Strikeouts',
 'Home Stolen Bases',
 'Home Caught Stealing',
 'Home Grounded into Double Play',
 'Home Awarded First (interference)',
 'Home Left on Base',
 'Home Pitchers Used',
 'Home Earned Runs (individual)',
 'Home Earned Runs (Team)',
 'Home Wild Pitches',
 'Home Balks',
 'Home Outs',
 'Home Assists',
 'Home Errors',
 'Home Passed Balls',
 'Home Double Plays',
 'Home Triple Plays',
 'Acquisition Info']

,Date,Day of Week,Visitor,Visitor Division,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,...,Home Earned Runs (Team),Home Wild Pitches,Home Balks,Home Outs,Home Assists,Home Errors,Home Passed Balls,Home Double Plays,Home Triple Plays,Acquisition Info
51,4/10/2009,Fri,PHI,NL,COL,NL,3,10,51,1.0,...,3,1,0,27,15,1,0,3,0,Y
66,4/11/2009,Sat,PHI,NL,COL,NL,8,4,54,0.0,...,8,0,0,27,6,0,0,0,0,Y
81,4/12/2009,Sun,PHI,NL,COL,NL,7,5,54,1.0,...,7,0,0,27,13,0,0,3,0,Y
229,4/24/2009,Fri,LAN,NL,COL,NL,6,5,54,0.0,...,6,1,0,27,12,0,0,2,0,Y
244,4/25/2009,Sat,LAN,NL,COL,NL,6,5,54,0.0,...,6,0,0,27,6,0,0,0,0,Y
259,4/26/2009,Sun,LAN,NL,COL,NL,4,10,51,1.0,...,4,0,0,27,9,1,0,1,0,Y
275,4/27/2009,Mon,SDN,NL,COL,NL,7,12,51,0.0,...,6,0,0,27,8,1,0,1,0,Y
288,4/28/2009,Tue,SDN,NL,COL,NL,4,3,54,0.0,...,4,0,0,27,14,1,0,0,0,Y
304,4/29/2009,Wed,SDN,NL,COL,NL,5,7,51,1.0,...,5,0,0,27,12,0,0,1,0,Y
396,5/6/2009,Wed,SFN,NL,COL,NL,1,11,51,0.0,...,1,1,0,27,10,0,0,1,0,Y
410,5/7/2009,Thu,SFN,NL,COL,NL,8,3,54,1.0,...,5,0,0,27,15,3,0,0,0,Y
426,5/8/2009,Fri,FLO,NL,COL,NL,8,3,54,0.0,...,8,1,0,27,12,0,0,0,0,Y
441,5/9/2009,Sat,FLO,NL,COL,NL,3,1,54,0.0,...,3,0,0,27,8,1,0,0,0,Y
456,5/10/2009,Sun,FLO,NL,COL,NL,2,3,51,1.0,...,1,0,0,27,15,1,0,0,0,Y
475,5/12/2009,Tue,HOU,NL,COL,NL,1,12,51,0.0,...,1,1,0,27,13,0,0,0,0,Y
490,5/13/2009,Wed,HOU,NL,COL,NL,15,11,54,0.0,...,15,0,0,27,8,0,0,0,0,Y
504,5/14/2009,Thu,HOU,NL,COL,NL,5,3,54,1.0,...,2,0,0,27,11,3,0,1,0,Y
659,5/25/2009,Mon,LAN,NL,COL,NL,16,6,54,1.0,...,16,1,0,27,10,1,0,0,0,Y
674,5/26/2009,Tue,LAN,NL,COL,NL,7,1,54,0.0,...,6,0,0,27,17,1,0,1,0,Y
689,5/27/2009,Wed,LAN,NL,COL,NL,8,6,54,1.0,...,7,0,0,27,17,1,0,3,0,Y
708,5/29/2009,Fri,SDN,NL,COL,NL,0,3,51,0.0,...,0,0,0,27,18,0,0,2,0,Y
724,5/30/2009,Sat,SDN,NL,COL,NL,7,8,53,0.0,...,6,1,0,27,11,1,0,1,0,Y
739,5/31/2009,Sun,SDN,NL,COL,NL,5,2,54,1.0,...,5,0,0,27,10,0,0,0,0,Y
900,6/12/2009,Fri,SEA,AL,COL,NL,4,6,51,0.0,...,4,0,0,27,17,0,0,2,0,Y
915,6/13/2009,Sat,SEA,AL,COL,NL,3,5,51,0.0,...,3,2,0,27,15,0,0,1,0,Y
930,6/14/2009,Sun,SEA,AL,COL,NL,1,7,51,1.0,...,1,0,0,27,9,0,0,1,0,Y
946,6/16/2009,Tue,TBA,AL,COL,NL,12,4,54,0.0,...,12,0,0,27,8,0,0,0,0,Y
961,6/17/2009,Wed,TBA,AL,COL,NL,3,5,51,0.0,...,3,0,0,27,15,2,0,1,0,Y
976,6/18/2009,Thu,TBA,AL,COL,NL,3,4,51,1.0,...,3,0,0,27,4,2,0,0,0,Y
989,6/19/2009,Fri,PIT,NL,COL,NL,3,7,51,0.0,...,3,0,0,27,19,0,0,0,0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23545,8/6/2018,Mon,PIT,NL,COL,NL,0,2,51,0.0,...,0,0,0,27,10,0,0,1,0,NaN
23555,8/7/2018,Tue,PIT,NL,COL,NL,10,2,54,0.0,...,10,0,0,27,11,1,0,0,0,NaN
23571,8/8/2018,Wed,PIT,NL,COL,NL,4,3,54,1.0,...,3,0,0,27,12,2,0,0,0,NaN
23584,8/9/2018,Thu,LAN,NL,COL,NL,8,5,54,0.0,...,8,1,0,27,7,1,0,0,0,NaN
23596,8/10/2018,Fri,LAN,NL,COL,NL,4,5,51,0.0,...,4,1,0,27,14,0,0,1,0,NaN
23611,8/11/2018,Sat,LAN,NL,COL,NL,2,3,53,0.0,...,2,0,0,27,10,0,0,1,0,NaN
23627,8/12/2018,Sun,LAN,NL,COL,NL,3,4,53,1.0,...,3,0,0,27,9,0,0,1,0,NaN
23745,8/21/2018,Tue,SDN,NL,COL,NL,4,3,54,0.0,...,4,0,0,27,7,1,1,0,0,NaN
23760,8/22/2018,Wed,SDN,NL,COL,NL,2,6,51,0.0,...,2,0,0,27,8,0,0,0,0,NaN
23775,8/23/2018,Thu,SDN,NL,COL,NL,3,4,53,1.0,...,2,0,0,27,14,1,0,2,0,NaN
23785,8/24/2018,Fri,SLN,NL,COL,NL,7,5,54,0.0,...,7,0,0,27,11,1,1,0,0,NaN
23800,8/25/2018,Sat,SLN,NL,COL,NL,1,9,51,0.0,...,1,1,0,27,9,0,0,1,0,NaN
23816,8/26/2018,Sun,SLN,NL,COL,NL,12,3,54,1.0,...,8,1,0,27,14,2,0,1,0,NaN
23922,9/3/2018,Mon,SFN,NL,COL,NL,8,9,51,1.0,...,8,1,0,27,8,2,0,0,0,NaN
23937,9/4/2018,Tue,SFN,NL,COL,NL,2,6,51,0.0,...,2,0,0,27,9,0,0,1,0,NaN
23951,9/5/2018,Wed,SFN,NL,COL,NL,3,5,51,0.0,...,3,0,0,27,8,0,0,1,0,NaN
23970,9/7/2018,Fri,LAN,NL,COL,NL,4,2,54,0.0,...,2,0,1,27,13,1,0,2,0,NaN
23984,9/8/2018,Sat,LAN,NL,COL,NL,2,4,51,0.0,...,2,0,0,27,9,0,0,1,0,NaN
24000,9/9/2018,Sun,LAN,NL,COL,NL,9,6,54,1.0,...,8,2,0,27,8,1,0,0,0,NaN
24013,9/10/2018,Mon,ARI,NL,COL,NL,2,13,51,0.0,...,1,0,0,27,10,1,0,1,0,NaN
24023,9/11/2018,Tue,ARI,NL,COL,NL,6,3,54,0.0,...,6,0,0,27,12,0,0,2,0,NaN
24039,9/12/2018,Wed,ARI,NL,COL,NL,4,5,52,0.0,...,4,0,0,27,8,0,0,1,0,NaN
24052,9/13/2018,Thu,ARI,NL,COL,NL,3,10,51,1.0,...,3,0,0,27,14,1,0,3,0,NaN
24202,9/24/2018,Mon,PHI,NL,COL,NL,1,10,51,0.0,...,1,0,0,27,12,0,0,2,0,NaN
24215,9/25/2018,Tue,PHI,NL,COL,NL,3,10,51,0.0,...,2,1,0,27,12,2,0,2,0,NaN
24229,9/26/2018,Wed,PHI,NL,COL,NL,0,14,51,0.0,...,0,0,0,27,11,1,0,1,0,NaN
24243,9/27/2018,Thu,PHI,NL,COL,NL,3,5,51,1.0,...,3,0,0,27,5,0,0,0,0,NaN
24251,9/28/2018,Fri,WAS,NL,COL,NL,2,5,51,0.0,...,2,0,0,27,9,0,0,1,0,NaN
24267,9/29/2018,Sat,WAS,NL,COL,NL,12,2,54,0.0,...,12,0,0,27,14,1,0,2,0,NaN
24283,9/30/2018,Sun,WAS,NL,COL,NL,0,12,51,1.0,...,0,0,0,27,12,0,0,3,0,NaN

In [5]:

W.columns=['ObsDate',
 'ActHigh',
 'ActLow',
 'ActAvg',
 'NormHigh',
 'NormLow',
 'NormAvg.',
 'NormDept',
 'RecHigh',
 'RecYear',
 'RecLow',
 'RecYear1',
 'PrecipAmt',
 'SnowAmt',
 'SnowGround',
 'HeatDegDay',
 'CoolDegDay',
 'Unnamed: 17']

In [6]:
W.ObsDate = pd.to_datetime(W.ObsDate)
COL.Date = pd.to_datetime(COL.Date)

/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [7]:
W.ObsDate.head()
COL.Date.head()

0   2009-04-01
1   2009-04-02
2   2009-04-03
3   2009-04-04
4   2009-04-05
Name: ObsDate, dtype: datetime64[ns]

51    2009-04-10
66    2009-04-11
81    2009-04-12
229   2009-04-24
244   2009-04-25
Name: Date, dtype: datetime64[ns]

In [8]:
month=W.ObsDate.astype('datetime64[M]')

In [9]:
W['Month']=W.ObsDate.astype('datetime64[M]')
COL['Month']=COL.Date.astype('datetime64[M]')

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [10]:
W.head()
COL.head()
W.drop('NormLow',axis=1,inplace=True)
W.drop('RecHigh',axis=1,inplace=True)
W.drop('RecYear',axis=1,inplace=True)
W.drop('RecLow',axis=1,inplace=True)
W.drop('RecYear1',axis=1,inplace=True)
W.drop('SnowGround',axis=1,inplace=True)
W.drop('HeatDegDay',axis=1,inplace=True)
W.drop('CoolDegDay',axis=1,inplace=True)
W.drop('Unnamed: 17',axis=1,inplace=True)

,ObsDate,ActHigh,ActLow,ActAvg,NormHigh,NormLow,NormAvg.,NormDept,RecHigh,RecYear,RecLow,RecYear1,PrecipAmt,SnowAmt,SnowGround,HeatDegDay,CoolDegDay,Unnamed: 17,Month
0,2009-04-01,46,23,35,61,32,46,-11,M,M,M,M,0.17,0.7,4.0,30,0,NaN,2009-04-01
1,2009-04-02,55,19,37,61,32,46,-9,M,M,M,M,0.1,0.0,3.0,28,0,NaN,2009-04-01
2,2009-04-03,55,32,44,61,32,47,-3,M,M,M,M,0.3,0.4,3.0,21,0,NaN,2009-04-01
3,2009-04-04,32,19,26,61,32,47,-21,M,M,M,M,0.4,1.8,4.0,39,0,NaN,2009-04-01
4,2009-04-05,34,18,26,62,32,47,-21,M,M,M,M,0.04,0.4,5.0,39,0,NaN,2009-04-01

,Date,Day of Week,Visitor,Visitor Division,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,...,Home Wild Pitches,Home Balks,Home Outs,Home Assists,Home Errors,Home Passed Balls,Home Double Plays,Home Triple Plays,Acquisition Info,Month
51,2009-04-10,Fri,PHI,NL,COL,NL,3,10,51,1.0,...,1,0,27,15,1,0,3,0,Y,2009-04-01
66,2009-04-11,Sat,PHI,NL,COL,NL,8,4,54,0.0,...,0,0,27,6,0,0,0,0,Y,2009-04-01
81,2009-04-12,Sun,PHI,NL,COL,NL,7,5,54,1.0,...,0,0,27,13,0,0,3,0,Y,2009-04-01
229,2009-04-24,Fri,LAN,NL,COL,NL,6,5,54,0.0,...,1,0,27,12,0,0,2,0,Y,2009-04-01
244,2009-04-25,Sat,LAN,NL,COL,NL,6,5,54,0.0,...,0,0,27,6,0,0,0,0,Y,2009-04-01

In [11]:
COL.drop('If Completed at Later Date',axis=1,inplace=True)
COL.drop('Stadium ID',axis=1,inplace=True)
COL.drop('Visitor Runs (by inning)',axis=1,inplace=True)
COL.drop('Home Runs (by inning)',axis=1,inplace=True)
COL.drop('Visitor At-Bats',axis=1,inplace=True)
COL.drop('Visitor Hits',axis=1,inplace=True)
COL.drop('Visitor Doubles',axis=1,inplace=True)
COL.drop('Visitor Triples',axis=1,inplace=True)
COL.drop('Visitor RBIs',axis=1,inplace=True)
COL.drop('Visitor Sacrifice Hits',axis=1,inplace=True)
COL.drop('Visitor Sacrifice Flies',axis=1,inplace=True)
COL.drop('Visitor HBP',axis=1,inplace=True)
COL.drop('Visitor Walks',axis=1,inplace=True)
COL.drop('Visitor Walks (intentional)',axis=1,inplace=True)
COL.drop('Visitor Strikeouts',axis=1,inplace=True)
COL.drop('Visitor Stolen Bases',axis=1,inplace=True)
COL.drop('Visitor Caught Stealing',axis=1,inplace=True)
COL.drop('Visitor Ground into Double Play',axis=1,inplace=True)
COL.drop('Visitor Awarded First (interference)',axis=1,inplace=True)
COL.drop('Visitor Left on Base',axis=1,inplace=True)
COL.drop('Visitor Earned Runs (individual)',axis=1,inplace=True)
COL.drop('Visitor Earned Runs (team)',axis=1,inplace=True)
COL.drop('Visitor Wild Pitch',axis=1,inplace=True)
COL.drop('Visitor Balks',axis=1,inplace=True)
COL.drop('Visitor Outs',axis=1,inplace=True)
COL.drop('Visitor Assists',axis=1,inplace=True)
COL.drop('Visitor Passed Balls',axis=1,inplace=True)
COL.drop('Visitor Double Plays',axis=1,inplace=True)
COL.drop('Visitor Triple Plays',axis=1,inplace=True)
COL.drop('Home At-Bats',axis=1,inplace=True)
COL.drop('Home Hits',axis=1,inplace=True)
COL.drop('Home Doubles',axis=1,inplace=True)
COL.drop('Home Triples',axis=1,inplace=True)
COL.drop('Home RBIs',axis=1,inplace=True)
COL.drop('Home Sacrifice Hits',axis=1,inplace=True)
COL.drop('Home Sacrifice Flies',axis=1,inplace=True)
COL.drop('Home Hit by Pitch',axis=1,inplace=True)
COL.drop('Home Walks',axis=1,inplace=True)
COL.drop('Home Walks (intentional)',axis=1,inplace=True)
COL.drop('Home Strikeouts',axis=1,inplace=True)
COL.drop('Home Stolen Bases',axis=1,inplace=True)
COL.drop('Home Caught Stealing',axis=1,inplace=True)
COL.drop('Home Grounded into Double Play',axis=1,inplace=True)
COL.drop('Home Awarded First (interference)',axis=1,inplace=True)
COL.drop('Home Left on Base',axis=1,inplace=True)
COL.drop('Home Earned Runs (individual)',axis=1,inplace=True)
COL.drop('Home Earned Runs (Team)',axis=1,inplace=True)
COL.drop('Home Wild Pitches',axis=1,inplace=True)
COL.drop('Home Balks',axis=1,inplace=True)
COL.drop('Home Outs',axis=1,inplace=True)
COL.drop('Home Assists',axis=1,inplace=True)
COL.drop('Home Passed Balls',axis=1,inplace=True)
COL.drop('Home Double Plays',axis=1,inplace=True)
COL.drop('Home Triple Plays',axis=1,inplace=True)
COL.drop('Acquisition Info',axis=1,inplace=True)
COL.drop('Visitor Division',axis=1,inplace=True)

/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [12]:
COL.set_index('Date',inplace=True)
W.set_index('ObsDate',inplace=True)
COW=COL.merge(W,left_on='Date',right_index=True)

In [13]:
April2009 = W.loc[W.Month=="2009-04-01",]
May2009= W.loc[W.Month=="2009-05-01",]
June2009= W.loc[W.Month=="2009-06-01",]
July2009= W.loc[W.Month=="2009-07-01",]
August2009= W.loc[W.Month=="2009-08-01",]
September2009 = W.loc[W.Month=="2009-09-01",]
October2009 = W.loc[W.Month=="2009-10-01",]

April2010 = W.loc[W.Month=="2010-04-01",]
May2010= W.loc[W.Month=="2010-05-01",]
June2010= W.loc[W.Month=="2010-06-01",]
July2010= W.loc[W.Month=="2010-07-01",]
August2010= W.loc[W.Month=="2010-08-01",]
September2010 = W.loc[W.Month=="2010-09-01",]
October2010 = W.loc[W.Month=="2010-10-01",]

April2011 = W.loc[W.Month=="2011-04-01",]
May2011= W.loc[W.Month=="2011-05-01",]
June2011= W.loc[W.Month=="2011-06-01",]
July2011= W.loc[W.Month=="2011-07-01",]
August2011= W.loc[W.Month=="2011-08-01",]
September2011 = W.loc[W.Month=="2011-09-01",]
October2011 = W.loc[W.Month=="2011-10-01",]

April2012 = W.loc[W.Month=="2012-04-01",]
May2012= W.loc[W.Month=="2012-05-01",]
June2012= W.loc[W.Month=="2012-06-01",]
July2012= W.loc[W.Month=="2012-07-01",]
August2012= W.loc[W.Month=="2012-08-01",]
September2012 = W.loc[W.Month=="2012-09-01",]
October2012 = W.loc[W.Month=="2012-10-01",]

April2013 = W.loc[W.Month=="2013-04-01",]
May2013= W.loc[W.Month=="2013-05-01",]
June2013= W.loc[W.Month=="2013-06-01",]
July2013= W.loc[W.Month=="2013-07-01",]
August2013= W.loc[W.Month=="2013-08-01",]
September2013 = W.loc[W.Month=="2013-09-01",]
October2013 = W.loc[W.Month=="2013-10-01",]

April2014 = W.loc[W.Month=="2014-04-01",]
May2014= W.loc[W.Month=="2014-05-01",]
June2014= W.loc[W.Month=="2014-06-01",]
July2014= W.loc[W.Month=="2014-07-01",]
August2014= W.loc[W.Month=="2014-08-01",]
September2014 = W.loc[W.Month=="2014-09-01",]
October2014 = W.loc[W.Month=="2014-10-01",]

April2015 = W.loc[W.Month=="2015-04-01",]
May2015= W.loc[W.Month=="2015-05-01",]
June2015= W.loc[W.Month=="2015-06-01",]
July2015= W.loc[W.Month=="2015-07-01",]
August2015= W.loc[W.Month=="2015-08-01",]
September2015 = W.loc[W.Month=="2015-09-01",]
October2015 = W.loc[W.Month=="2015-10-01",]

April2016 = W.loc[W.Month=="2016-04-01",]
May2016= W.loc[W.Month=="2016-05-01",]
June2016= W.loc[W.Month=="2016-06-01",]
July2016= W.loc[W.Month=="2016-07-01",]
August2016= W.loc[W.Month=="2016-08-01",]
September2016 = W.loc[W.Month=="2016-09-01",]
October2016 = W.loc[W.Month=="2016-10-01",]

April2017 = W.loc[W.Month=="2017-04-01",]
May2017= W.loc[W.Month=="2017-05-01",]
June2017= W.loc[W.Month=="2017-06-01",]
July2017= W.loc[W.Month=="2017-07-01",]
August2017= W.loc[W.Month=="2017-08-01",]
September2017 = W.loc[W.Month=="2017-09-01",]
October2017 = W.loc[W.Month=="2017-10-01",]

April2018 = W.loc[W.Month=="2018-04-01",]
May2018= W.loc[W.Month=="2018-05-01",]
June2018= W.loc[W.Month=="2018-06-01",]
July2018= W.loc[W.Month=="2018-07-01",]
August2018= W.loc[W.Month=="2018-08-01",]
September2018 = W.loc[W.Month=="2018-09-01",]
October2018 = W.loc[W.Month=="2018-10-01",]

In [14]:
COL.head()

,Day of Week,Visitor,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,Attendance,Game Length (minutes),Visitor Homeruns,Visitor Pitchers Used,Visitor Errors,Home Homeruns,Home Pitchers Used,Home Errors,Month
Date,,,,,,,,,,,,,,,,,
2009-04-10,Fri,PHI,COL,NL,3,10,51,1.0,49427.0,154,1,4,0,1,3,1,2009-04-01
2009-04-11,Sat,PHI,COL,NL,8,4,54,0.0,35251.0,181,1,3,0,3,6,0,2009-04-01
2009-04-12,Sun,PHI,COL,NL,7,5,54,1.0,21628.0,196,2,6,0,1,5,0,2009-04-01
2009-04-24,Fri,LAN,COL,NL,6,5,54,0.0,36151.0,225,0,4,1,1,5,0,2009-04-01
2009-04-25,Sat,LAN,COL,NL,6,5,54,0.0,31476.0,181,0,2,0,1,5,0,2009-04-01

In [15]:
April2009B = COL.loc[COL.Month=="2009-04-01",]
May2009B= COL.loc[COL.Month=="2009-05-01",]
June2009B= COL.loc[COL.Month=="2009-06-01",]
July2009B= COL.loc[COL.Month=="2009-07-01",]
August2009B= COL.loc[COL.Month=="2009-08-01",]
September2009B = COL.loc[COL.Month=="2009-09-01",]
October2009B = COL.loc[COL.Month=="2009-10-01",]

April2010B = COL.loc[COL.Month=="2010-04-01",]
May2010B= COL.loc[COL.Month=="2010-05-01",]
June2010B= COL.loc[COL.Month=="2010-06-01",]
July2010B= COL.loc[COL.Month=="2010-07-01",]
August2010B= COL.loc[COL.Month=="2010-08-01",]
September2010B = COL.loc[COL.Month=="2010-09-01",]
October2010B = COL.loc[COL.Month=="2010-10-01",]

April2011B = COL.loc[COL.Month=="2011-04-01",]
May2011B= COL.loc[COL.Month=="2011-05-01",]
June2011B= COL.loc[COL.Month=="2011-06-01",]
July2011B= COL.loc[COL.Month=="2011-07-01",]
August2011B= COL.loc[COL.Month=="2011-08-01",]
September2011B = COL.loc[COL.Month=="2011-09-01",]
October2011B = COL.loc[COL.Month=="2011-10-01",]

April2012B = COL.loc[COL.Month=="2012-04-01",]
May2012B= COL.loc[COL.Month=="2012-05-01",]
June2012B= COL.loc[COL.Month=="2012-06-01",]
July2012B= COL.loc[COL.Month=="2012-07-01",]
August2012B= COL.loc[COL.Month=="2012-08-01",]
September2012B = COL.loc[COL.Month=="2012-09-01",]
October2012B = COL.loc[COL.Month=="2012-10-01",]

April2013B = COL.loc[COL.Month=="2013-04-01",]
May2013B= COL.loc[COL.Month=="2013-05-01",]
June2013B= COL.loc[COL.Month=="2013-06-01",]
July2013B= COL.loc[COL.Month=="2013-07-01",]
August2013B= COL.loc[COL.Month=="2013-08-01",]
September2013B = COL.loc[COL.Month=="2013-09-01",]
October2013B = COL.loc[COL.Month=="2013-10-01",]

April2014B = COL.loc[COL.Month=="2014-04-01",]
May2014B= COL.loc[COL.Month=="2014-05-01",]
June2014B= COL.loc[COL.Month=="2014-06-01",]
July2014B= COL.loc[COL.Month=="2014-07-01",]
August2014B= COL.loc[COL.Month=="2014-08-01",]
September2014B = COL.loc[COL.Month=="2014-09-01",]
October2014B = COL.loc[COL.Month=="2014-10-01",]

April2015B = COL.loc[COL.Month=="2015-04-01",]
May2015B= COL.loc[COL.Month=="2015-05-01",]
June2015B= COL.loc[COL.Month=="2015-06-01",]
July2015B= COL.loc[COL.Month=="2015-07-01",]
August2015B= COL.loc[COL.Month=="2015-08-01",]
September2015B = COL.loc[COL.Month=="2015-09-01",]
October2015B = COL.loc[COL.Month=="2015-10-01",]

April2016B = COL.loc[COL.Month=="2016-04-01",]
May2016B= COL.loc[COL.Month=="2016-05-01",]
June2016B= COL.loc[COL.Month=="2016-06-01",]
July2016B= COL.loc[COL.Month=="2016-07-01",]
August2016B= COL.loc[COL.Month=="2016-08-01",]
September2016B = COL.loc[COL.Month=="2016-09-01",]
October2016B = COL.loc[COL.Month=="2016-10-01",]

April2017B = COL.loc[COL.Month=="2017-04-01",]
May2017B= COL.loc[COL.Month=="2017-05-01",]
June2017B= COL.loc[COL.Month=="2017-06-01",]
July2017B= COL.loc[COL.Month=="2017-07-01",]
August2017B= COL.loc[COL.Month=="2017-08-01",]
September2017B = COL.loc[COL.Month=="2017-09-01",]
October2017B = COL.loc[COL.Month=="2017-10-01",]

April2018B = COL.loc[COL.Month=="2018-04-01",]
May2018B= COL.loc[COL.Month=="2018-05-01",]
June2018B= COL.loc[COL.Month=="2018-06-01",]
July2018B= COL.loc[COL.Month=="2018-07-01",]
August2018B= COL.loc[COL.Month=="2018-08-01",]
September2018B = COL.loc[COL.Month=="2018-09-01",]
October2018B = COL.loc[COL.Month=="2018-10-01",]

In [16]:
COW.head()
COW.rename(columns={'Month_x':'Month'}, inplace=True)
COW.drop('Month_y',axis=1,inplace=True)

,Day of Week,Visitor,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,Attendance,Game Length (minutes),...,Month_x,ActHigh,ActLow,ActAvg,NormHigh,NormAvg.,NormDept,PrecipAmt,SnowAmt,Month_y
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-10,Fri,PHI,COL,NL,3,10,51,1.0,49427.0,154,...,2009-04-01,59,27,43,63,48,-5,0,0.0,2009-04-01
2009-04-11,Sat,PHI,COL,NL,8,4,54,0.0,35251.0,181,...,2009-04-01,57,36,47,63,48,-1,0,0.0,2009-04-01
2009-04-12,Sun,PHI,COL,NL,7,5,54,1.0,21628.0,196,...,2009-04-01,46,37,42,63,48,-6,0,0.0,2009-04-01
2009-04-24,Fri,LAN,COL,NL,6,5,54,0.0,36151.0,225,...,2009-04-01,66,37,52,66,52,0,0,0.0,2009-04-01
2009-04-25,Sat,LAN,COL,NL,6,5,54,0.0,31476.0,181,...,2009-04-01,46,39,43,67,52,-9,0,0.0,2009-04-01

In [17]:
April2009W = COW.loc[COW.Month=="2009-04-01",]
May2009W= COW.loc[COW.Month=="2009-05-01",]
June2009W= COW.loc[COW.Month=="2009-06-01",]
July2009W= COW.loc[COW.Month=="2009-07-01",]
August2009W= COW.loc[COW.Month=="2009-08-01",]
SeptemWer2009W = COW.loc[COW.Month=="2009-09-01",]
OctoWer2009W = COW.loc[COW.Month=="2009-10-01",]

April2010W = COW.loc[COW.Month=="2010-04-01",]
May2010W= COW.loc[COW.Month=="2010-05-01",]
June2010W= COW.loc[COW.Month=="2010-06-01",]
July2010W= COW.loc[COW.Month=="2010-07-01",]
August2010W= COW.loc[COW.Month=="2010-08-01",]
SeptemWer2010W = COW.loc[COW.Month=="2010-09-01",]
OctoWer2010W = COW.loc[COW.Month=="2010-10-01",]

April2011W = COW.loc[COW.Month=="2011-04-01",]
May2011W= COW.loc[COW.Month=="2011-05-01",]
June2011W= COW.loc[COW.Month=="2011-06-01",]
July2011W= COW.loc[COW.Month=="2011-07-01",]
August2011W= COW.loc[COW.Month=="2011-08-01",]
SeptemWer2011W = COW.loc[COW.Month=="2011-09-01",]
OctoWer2011W = COW.loc[COW.Month=="2011-10-01",]

April2012W = COW.loc[COW.Month=="2012-04-01",]
May2012W= COW.loc[COW.Month=="2012-05-01",]
June2012W= COW.loc[COW.Month=="2012-06-01",]
July2012W= COW.loc[COW.Month=="2012-07-01",]
August2012W= COW.loc[COW.Month=="2012-08-01",]
SeptemWer2012W = COW.loc[COW.Month=="2012-09-01",]
OctoWer2012W = COW.loc[COW.Month=="2012-10-01",]

April2013W = COW.loc[COW.Month=="2013-04-01",]
May2013W= COW.loc[COW.Month=="2013-05-01",]
June2013W= COW.loc[COW.Month=="2013-06-01",]
July2013W= COW.loc[COW.Month=="2013-07-01",]
August2013W= COW.loc[COW.Month=="2013-08-01",]
SeptemWer2013W = COW.loc[COW.Month=="2013-09-01",]
OctoWer2013W = COW.loc[COW.Month=="2013-10-01",]

April2014W = COW.loc[COW.Month=="2014-04-01",]
May2014W= COW.loc[COW.Month=="2014-05-01",]
June2014W= COW.loc[COW.Month=="2014-06-01",]
July2014W= COW.loc[COW.Month=="2014-07-01",]
August2014W= COW.loc[COW.Month=="2014-08-01",]
SeptemWer2014W = COW.loc[COW.Month=="2014-09-01",]
OctoWer2014W = COW.loc[COW.Month=="2014-10-01",]

April2015W = COW.loc[COW.Month=="2015-04-01",]
May2015W= COW.loc[COW.Month=="2015-05-01",]
June2015W= COW.loc[COW.Month=="2015-06-01",]
July2015W= COW.loc[COW.Month=="2015-07-01",]
August2015W= COW.loc[COW.Month=="2015-08-01",]
SeptemWer2015W = COW.loc[COW.Month=="2015-09-01",]
OctoWer2015W = COW.loc[COW.Month=="2015-10-01",]

April2016W = COW.loc[COW.Month=="2016-04-01",]
May2016W= COW.loc[COW.Month=="2016-05-01",]
June2016W= COW.loc[COW.Month=="2016-06-01",]
July2016W= COW.loc[COW.Month=="2016-07-01",]
August2016W= COW.loc[COW.Month=="2016-08-01",]
SeptemWer2016W = COW.loc[COW.Month=="2016-09-01",]
OctoWer2016W = COW.loc[COW.Month=="2016-10-01",]

April2017W = COW.loc[COW.Month=="2017-04-01",]
May2017W= COW.loc[COW.Month=="2017-05-01",]
June2017W= COW.loc[COW.Month=="2017-06-01",]
July2017W= COW.loc[COW.Month=="2017-07-01",]
August2017W= COW.loc[COW.Month=="2017-08-01",]
SeptemWer2017W = COW.loc[COW.Month=="2017-09-01",]
OctoWer2017W = COW.loc[COW.Month=="2017-10-01",]

April2018W = COW.loc[COW.Month=="2018-04-01",]
May2018W= COW.loc[COW.Month=="2018-05-01",]
June2018W= COW.loc[COW.Month=="2018-06-01",]
July2018W= COW.loc[COW.Month=="2018-07-01",]
August2018W= COW.loc[COW.Month=="2018-08-01",]
SeptemWer2018W = COW.loc[COW.Month=="2018-09-01",]
OctoWer2018W = COW.loc[COW.Month=="2018-10-01",]

In [18]:
COL.head()

,Day of Week,Visitor,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,Attendance,Game Length (minutes),Visitor Homeruns,Visitor Pitchers Used,Visitor Errors,Home Homeruns,Home Pitchers Used,Home Errors,Month
Date,,,,,,,,,,,,,,,,,
2009-04-10,Fri,PHI,COL,NL,3,10,51,1.0,49427.0,154,1,4,0,1,3,1,2009-04-01
2009-04-11,Sat,PHI,COL,NL,8,4,54,0.0,35251.0,181,1,3,0,3,6,0,2009-04-01
2009-04-12,Sun,PHI,COL,NL,7,5,54,1.0,21628.0,196,2,6,0,1,5,0,2009-04-01
2009-04-24,Fri,LAN,COL,NL,6,5,54,0.0,36151.0,225,0,4,1,1,5,0,2009-04-01
2009-04-25,Sat,LAN,COL,NL,6,5,54,0.0,31476.0,181,0,2,0,1,5,0,2009-04-01

In [19]:
COL.head()
W.head()

,Day of Week,Visitor,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,Attendance,Game Length (minutes),Visitor Homeruns,Visitor Pitchers Used,Visitor Errors,Home Homeruns,Home Pitchers Used,Home Errors,Month
Date,,,,,,,,,,,,,,,,,
2009-04-10,Fri,PHI,COL,NL,3,10,51,1.0,49427.0,154,1,4,0,1,3,1,2009-04-01
2009-04-11,Sat,PHI,COL,NL,8,4,54,0.0,35251.0,181,1,3,0,3,6,0,2009-04-01
2009-04-12,Sun,PHI,COL,NL,7,5,54,1.0,21628.0,196,2,6,0,1,5,0,2009-04-01
2009-04-24,Fri,LAN,COL,NL,6,5,54,0.0,36151.0,225,0,4,1,1,5,0,2009-04-01
2009-04-25,Sat,LAN,COL,NL,6,5,54,0.0,31476.0,181,0,2,0,1,5,0,2009-04-01

,ActHigh,ActLow,ActAvg,NormHigh,NormAvg.,NormDept,PrecipAmt,SnowAmt,Month
ObsDate,,,,,,,,,
2009-04-01,46,23,35,61,46,-11,0.17,0.7,2009-04-01
2009-04-02,55,19,37,61,46,-9,0.1,0.0,2009-04-01
2009-04-03,55,32,44,61,47,-3,0.3,0.4,2009-04-01
2009-04-04,32,19,26,61,47,-21,0.4,1.8,2009-04-01
2009-04-05,34,18,26,62,47,-21,0.04,0.4,2009-04-01

In [20]:
COL['Extra Innings']=COL['Game Length (outs)'].apply(lambda x: 0 if x <= 54 else 1)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [21]:
COL.head()

,Day of Week,Visitor,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,Attendance,Game Length (minutes),Visitor Homeruns,Visitor Pitchers Used,Visitor Errors,Home Homeruns,Home Pitchers Used,Home Errors,Month,Extra Innings
Date,,,,,,,,,,,,,,,,,,
2009-04-10,Fri,PHI,COL,NL,3,10,51,1.0,49427.0,154,1,4,0,1,3,1,2009-04-01,0
2009-04-11,Sat,PHI,COL,NL,8,4,54,0.0,35251.0,181,1,3,0,3,6,0,2009-04-01,0
2009-04-12,Sun,PHI,COL,NL,7,5,54,1.0,21628.0,196,2,6,0,1,5,0,2009-04-01,0
2009-04-24,Fri,LAN,COL,NL,6,5,54,0.0,36151.0,225,0,4,1,1,5,0,2009-04-01,0
2009-04-25,Sat,LAN,COL,NL,6,5,54,0.0,31476.0,181,0,2,0,1,5,0,2009-04-01,0

In [22]:
April2009.mean()
May2009.mean()
June2009.mean()
July2009.mean()
August2009.mean()
September2009.mean()
October2009.mean()

April2010.mean()
May2010.mean()
June2010.mean()
July2010.mean()
August2010.mean()
September2010.mean()
October2010.mean()

April2011.mean()
May2011.mean()
June2011.mean()
July2011.mean()
August2011.mean()
September2011.mean()
October2011.mean()

April2012.mean()
May2012.mean()
June2012.mean()
July2012.mean()
August2012.mean()
September2012.mean()
October2012.mean()

April2013.mean()
May2013.mean()
June2013.mean()
July2013.mean()
August2013.mean()
September2013.mean()
October2013.mean()

April2014.mean()
May2014.mean()
June2014.mean()
July2014.mean()
August2014.mean()
September2014.mean()
October2014.mean()

April2015.mean()
May2015.mean()
June2015.mean()
July2015.mean()
August2015.mean()
September2015.mean()
October2015.mean()

April2016.mean()
May2016.mean()
June2016.mean()
July2016.mean()
August2016.mean()
September2016.mean()
October2016.mean()

April2017.mean()
May2017.mean()
June2017.mean()
July2017.mean()
August2017.mean()
September2017.mean()
October2017.mean()

April2018.mean()
May2018.mean()
June2018.mean()
July2018.mean()
August2018.mean()
September2018.mean()
October2018.mean()

ActHigh     56.833333
ActLow      34.000000
ActAvg      45.766667
NormHigh    64.200000
NormAvg.    49.466667
NormDept    -3.700000
SnowAmt      0.373333
dtype: float64

ActHigh     70.096774
ActLow      47.032258
ActAvg      58.838710
NormHigh    74.064516
NormAvg.    59.225806
NormDept    -0.387097
SnowAmt      0.000000
dtype: float64

ActHigh     75.666667
ActLow      52.000000
ActAvg      64.100000
NormHigh    85.066667
NormAvg.    68.933333
NormDept    -4.833333
SnowAmt      0.000000
dtype: float64

ActHigh     82.870968
ActLow      57.709677
ActAvg      70.580645
NormHigh    91.741935
NormAvg.    74.967742
NormDept    -4.387097
SnowAmt      0.000000
dtype: float64

ActHigh     83.612903
ActLow      56.903226
ActAvg      70.548387
NormHigh    89.322581
NormAvg.    73.258065
NormDept    -2.709677
SnowAmt      0.000000
dtype: float64

ActHigh     76.100000
ActLow      49.766667
ActAvg      63.266667
NormHigh    81.066667
NormAvg.    64.600000
NormDept    -1.333333
SnowAmt      0.000000
dtype: float64

ActHigh     53.838710
ActLow      31.838710
ActAvg      43.129032
NormHigh    68.129032
NormAvg.    52.612903
NormDept    -9.483871
SnowAmt      0.338710
dtype: float64

ActHigh     59.266667
ActLow      36.866667
ActAvg      48.300000
NormHigh    64.200000
NormAvg.    49.466667
NormDept    -1.166667
SnowAmt      0.110000
dtype: float64

ActHigh     65.741935
ActLow      42.096774
ActAvg      54.161290
NormHigh    74.064516
NormAvg.    59.225806
NormDept    -5.064516
SnowAmt      0.083871
dtype: float64

ActHigh     81.000000
ActLow      56.066667
ActAvg      68.833333
NormHigh    85.066667
NormAvg.    68.933333
NormDept    -0.100000
SnowAmt      0.000000
dtype: float64

ActHigh     86.967742
ActLow      61.161290
ActAvg      74.322581
NormHigh    91.741935
NormAvg.    74.967742
NormDept    -0.645161
SnowAmt      0.000000
dtype: float64

ActHigh     87.000000
ActLow      61.000000
ActAvg      74.354839
NormHigh    89.322581
NormAvg.    73.258065
NormDept     1.096774
SnowAmt      0.000000
dtype: float64

ActHigh     82.033333
ActLow      53.666667
ActAvg      68.166667
NormHigh    81.066667
NormAvg.    64.600000
NormDept     3.566667
SnowAmt      0.000000
dtype: float64

ActHigh     67.580645
ActLow      44.645161
ActAvg      56.354839
NormHigh    68.129032
NormAvg.    52.612903
NormDept     3.741935
SnowAmt      0.000000
dtype: float64

ActHigh     59.866667
ActLow      37.366667
ActAvg      48.800000
NormHigh    64.200000
NormAvg.    49.466667
NormDept    -0.666667
SnowAmt      0.230000
dtype: float64

ActHigh     62.322581
ActLow      42.806452
ActAvg      52.741935
NormHigh    74.064516
NormAvg.    59.225806
NormDept    -6.483871
SnowAmt      0.096774
dtype: float64

ActHigh     81.800000
ActLow      55.666667
ActAvg      69.066667
NormHigh    85.066667
NormAvg.    68.933333
NormDept     0.133333
SnowAmt      0.000000
dtype: float64

ActHigh     88.193548
ActLow      62.580645
ActAvg      75.774194
NormHigh    91.741935
NormAvg.    74.967742
NormDept     0.806452
SnowAmt      0.000000
dtype: float64

ActHigh     89.483871
ActLow      63.741935
ActAvg      77.000000
NormHigh    89.322581
NormAvg.    73.258065
NormDept     3.741935
SnowAmt      0.000000
dtype: float64

ActHigh     75.833333
ActLow      53.400000
ActAvg      64.933333
NormHigh    81.066667
NormAvg.    64.600000
NormDept     0.333333
SnowAmt      0.000000
dtype: float64

ActHigh     65.709677
ActLow      41.161290
ActAvg      53.741935
NormHigh    68.129032
NormAvg.    52.612903
NormDept     1.129032
SnowAmt      1.180645
dtype: float64

ActHigh     67.300000
ActLow      42.000000
ActAvg      54.933333
NormHigh    64.200000
NormAvg.    49.466667
NormDept     5.466667
SnowAmt      0.283333
dtype: float64

ActHigh     72.967742
ActLow      47.096774
ActAvg      60.225806
NormHigh    74.064516
NormAvg.    59.225806
NormDept     1.000000
SnowAmt      0.000000
dtype: float64

ActHigh     88.800000
ActLow      61.600000
ActAvg      75.500000
NormHigh    85.066667
NormAvg.    68.933333
NormDept     6.566667
SnowAmt      0.000000
dtype: float64

ActHigh     90.193548
ActLow      64.387097
ActAvg      77.677419
NormHigh    91.741935
NormAvg.    74.967742
NormDept     2.709677
SnowAmt      0.000000
dtype: float64

ActHigh     87.903226
ActLow      61.322581
ActAvg      74.870968
NormHigh    89.322581
NormAvg.    73.258065
NormDept     1.612903
SnowAmt      0.000000
dtype: float64

ActHigh     78.366667
ActLow      54.700000
ActAvg      66.766667
NormHigh    81.066667
NormAvg.    64.600000
NormDept     2.166667
SnowAmt      0.000000
dtype: float64

ActHigh     62.193548
ActLow      39.096774
ActAvg      50.870968
NormHigh    68.129032
NormAvg.    52.612903
NormDept    -1.741935
SnowAmt      0.645161
dtype: float64

ActHigh     54.400000
ActLow      31.933333
ActAvg      43.433333
NormHigh    64.200000
NormAvg.    49.466667
NormDept    -6.033333
SnowAmt      3.886667
dtype: float64

ActHigh     69.580645
ActLow      46.709677
ActAvg      58.354839
NormHigh    74.064516
NormAvg.    59.225806
NormDept    -0.870968
SnowAmt      0.600000
dtype: float64

ActHigh     84.500000
ActLow      56.533333
ActAvg      70.866667
NormHigh    85.066667
NormAvg.    68.933333
NormDept     1.933333
SnowAmt      0.000000
dtype: float64

ActHigh     86.064516
ActLow      61.967742
ActAvg      74.258065
NormHigh    91.741935
NormAvg.    74.967742
NormDept    -0.709677
SnowAmt      0.000000
dtype: float64

ActHigh     86.387097
ActLow      61.806452
ActAvg      74.322581
NormHigh    89.322581
NormAvg.    73.258065
NormDept     1.064516
SnowAmt      0.000000
dtype: float64

ActHigh     76.533333
ActLow      55.566667
ActAvg      66.300000
NormHigh    81.066667
NormAvg.    64.600000
NormDept     1.700000
SnowAmt      0.000000
dtype: float64

ActHigh     57.870968
ActLow      39.354839
ActAvg      48.903226
NormHigh    68.129032
NormAvg.    52.612903
NormDept    -3.709677
SnowAmt      0.677419
dtype: float64

ActHigh     15.500000
ActLow      60.900000
ActAvg      37.400000
NormHigh    49.366667
NormAvg.    34.666667
NormDept    49.466667
SnowAmt      0.025667
dtype: float64

ActHigh     16.000000
ActLow      68.935484
ActAvg      46.064516
NormHigh    57.741935
NormAvg.    44.354839
NormDept    59.225806
SnowAmt      0.045484
dtype: float64

ActHigh     15.500000
ActLow      81.633333
ActAvg      53.466667
NormHigh    67.866667
NormAvg.    52.900000
NormDept    68.933333
SnowAmt      0.012000
dtype: float64

ActHigh     16.000000
ActLow      85.161290
ActAvg      61.741935
NormHigh    73.677419
NormAvg.    58.225806
NormDept    74.967742
SnowAmt      0.039355
dtype: float64

ActHigh     16.000000
ActLow      82.677419
ActAvg      58.870968
NormHigh    71.032258
NormAvg.    57.161290
NormDept    73.258065
SnowAmt      0.024839
dtype: float64

ActHigh     15.500000
ActLow      76.966667
ActAvg      53.200000
NormHigh    65.333333
NormAvg.    48.000000
NormDept    64.600000
SnowAmt      0.039667
dtype: float64

ActHigh     16.000000
ActLow      68.677419
ActAvg      44.677419
NormHigh    56.935484
NormAvg.    37.064516
NormDept    52.612903
SnowAmt      0.012903
dtype: float64

ActHigh     15.500000
ActLow      60.233333
ActAvg      38.133333
NormHigh    49.500000
NormAvg.    34.666667
NormDept    49.466667
SnowAmt      0.053000
dtype: float64

ActHigh     16.000000
ActLow      61.354839
ActAvg      42.903226
NormHigh    52.419355
NormAvg.    44.354839
NormDept    59.225806
SnowAmt      0.101935
dtype: float64

ActHigh     15.500000
ActLow      81.166667
ActAvg      57.800000
NormHigh    69.766667
NormAvg.    52.900000
NormDept    68.933333
SnowAmt      0.071667
dtype: float64

ActHigh     16.000000
ActLow      84.193548
ActAvg      59.258065
NormHigh    72.096774
NormAvg.    58.225806
NormDept    74.967742
SnowAmt      0.040645
dtype: float64

ActHigh     16.000000
ActLow      86.935484
ActAvg      59.645161
NormHigh    73.548387
NormAvg.    57.161290
NormDept    73.258065
SnowAmt      0.026452
dtype: float64

ActHigh     15.500000
ActLow      83.366667
ActAvg      56.566667
NormHigh    70.233333
NormAvg.    48.000000
NormDept    64.600000
SnowAmt      0.006000
dtype: float64

ActHigh     16.000000
ActLow      67.419355
ActAvg      47.032258
NormHigh    57.516129
NormAvg.    37.064516
NormDept    52.612903
SnowAmt      0.042581
dtype: float64

ActHigh     15.500000
ActLow      58.166667
ActAvg      38.333333
NormHigh    48.566667
NormAvg.    34.666667
NormDept    49.466667
SnowAmt      0.091667
dtype: float64

ActHigh     16.000000
ActLow      65.064516
ActAvg      43.322581
NormHigh    54.516129
NormAvg.    44.354839
NormDept    59.225806
SnowAmt      0.049355
dtype: float64

ActHigh     15.500000
ActLow      85.333333
ActAvg      58.566667
NormHigh    72.166667
NormAvg.    52.900000
NormDept    68.933333
SnowAmt      0.044000
dtype: float64

ActHigh     16.000000
ActLow      89.709677
ActAvg      61.354839
NormHigh    75.774194
NormAvg.    58.225806
NormDept    74.967742
SnowAmt      0.022258
dtype: float64

ActHigh     16.000000
ActLow      84.290323
ActAvg      58.161290
NormHigh    71.483871
NormAvg.    57.161290
NormDept    73.258065
SnowAmt      0.023548
dtype: float64

ActHigh     15.500000
ActLow      79.266667
ActAvg      53.233333
NormHigh    66.600000
NormAvg.    48.000000
NormDept    64.600000
SnowAmt      0.015000
dtype: float64

ActHigh     16.000000
ActLow      73.129032
ActAvg      45.580645
NormHigh    59.580645
NormAvg.    37.064516
NormDept    52.612903
SnowAmt      0.015161
dtype: float64

ActHigh     15.500000
ActLow      61.733333
ActAvg      37.200000
NormHigh    49.766667
NormAvg.    34.666667
NormDept    49.466667
SnowAmt      0.047333
dtype: float64

ActHigh     16.000000
ActLow      67.870968
ActAvg      43.645161
NormHigh    56.129032
NormAvg.    44.354839
NormDept    59.225806
SnowAmt      0.085484
dtype: float64

ActHigh     15.500000
ActLow      83.033333
ActAvg      56.533333
NormHigh    70.066667
NormAvg.    52.900000
NormDept    68.933333
SnowAmt      0.025000
dtype: float64

ActHigh     16.000000
ActLow      88.741935
ActAvg      61.612903
NormHigh    75.451613
NormAvg.    58.225806
NormDept    74.967742
SnowAmt      0.016774
dtype: float64

ActHigh     16.000000
ActLow      82.967742
ActAvg      58.548387
NormHigh    71.064516
NormAvg.    57.161290
NormDept    73.258065
SnowAmt      0.056774
dtype: float64

ActHigh     15.500000
ActLow      75.866667
ActAvg      52.266667
NormHigh    64.366667
NormAvg.    48.000000
NormDept    64.600000
SnowAmt      0.074333
dtype: float64

ActHigh     16.000000
ActLow      63.451613
ActAvg      38.612903
NormHigh    51.258065
NormAvg.    37.064516
NormDept    52.612903
SnowAmt      0.065806
dtype: float64

ActHigh     15.500000
ActLow      61.533333
ActAvg      35.533333
NormHigh    48.800000
NormAvg.    34.666667
NormDept    49.466667
SnowAmt      0.042333
dtype: float64

ActHigh     16.000000
ActLow      72.096774
ActAvg      49.193548
NormHigh    61.000000
NormAvg.    44.354839
NormDept    59.225806
SnowAmt      0.073548
dtype: float64

ActHigh     15.500000
ActLow      85.366667
ActAvg      58.766667
NormHigh    72.266667
NormAvg.    52.900000
NormDept    68.933333
SnowAmt      0.030000
dtype: float64

ActHigh     16.000000
ActLow      87.709677
ActAvg      61.838710
NormHigh    75.032258
NormAvg.    58.225806
NormDept    74.967742
SnowAmt      0.030645
dtype: float64

ActHigh     16.000000
ActLow      85.838710
ActAvg      59.677419
NormHigh    73.129032
NormAvg.    57.161290
NormDept    73.258065
SnowAmt      0.011935
dtype: float64

ActHigh     15.500000
ActLow      80.766667
ActAvg      55.333333
NormHigh    68.266667
NormAvg.    48.000000
NormDept    64.600000
SnowAmt      0.018000
dtype: float64

ActHigh     16.000000
ActLow      59.709677
ActAvg      39.000000
NormHigh    49.612903
NormAvg.    37.064516
NormDept    52.612903
SnowAmt      0.050000
dtype: float64

In [23]:
April2009B.mean()
May2009B.mean()
June2009B.mean()
July2009B.mean()
August2009B.mean()
September2009B.mean()
October2009B.mean()

April2010B.mean()
May2010B.mean()
June2010B.mean()
July2010B.mean()
August2010B.mean()
September2010B.mean()
October2010B.mean()

April2011B.mean()
May2011B.mean()
June2011B.mean()
July2011B.mean()
August2011B.mean()
September2011B.mean()
October2011B.mean()

April2012B.mean()
May2012B.mean()
June2012B.mean()
July2012B.mean()
August2012B.mean()
September2012B.mean()
October2012B.mean()

April2013B.mean()
May2013B.mean()
June2013B.mean()
July2013B.mean()
August2013B.mean()
September2013B.mean()
October2013B.mean()

April2014B.mean()
May2014B.mean()
June2014B.mean()
July2014B.mean()
August2014B.mean()
September2014B.mean()
October2014B.mean()

April2015B.mean()
May2015B.mean()
June2015B.mean()
July2015B.mean()
August2015B.mean()
September2015B.mean()
October2015B.mean()

April2016B.mean()
May2016B.mean()
June2016B.mean()
July2016B.mean()
August2016B.mean()
September2016B.mean()
October2016B.mean()

April2017B.mean()
May2017B.mean()
June2017B.mean()
July2017B.mean()
August2017B.mean()
September2017B.mean()
October2017B.mean()

April2018B.mean()
May2018B.mean()
June2018B.mean()
July2018B.mean()
August2018B.mean()
September2018B.mean()
October2018B.mean()

Visitor Score                5.555556
Home Score                   6.777778
Game Length (outs)          52.666667
Day or Night                 0.444444
Attendance               29702.111111
Game Length (minutes)      185.222222
Visitor Homeruns             1.000000
Visitor Pitchers Used        4.222222
Visitor Errors               0.222222
Home Homeruns                1.333333
Home Pitchers Used           4.444444
Home Errors                  0.444444
dtype: float64

Visitor Score                6.142857
Home Score                   5.214286
Game Length (outs)          53.071429
Day or Night                 0.428571
Attendance               26195.714286
Game Length (minutes)      178.714286
Visitor Homeruns             0.642857
Visitor Pitchers Used        3.785714
Visitor Errors               0.857143
Home Homeruns                1.142857
Home Pitchers Used           3.857143
Home Errors                  0.857143
dtype: float64

Visitor Score                4.444444
Home Score                   5.777778
Game Length (outs)          51.444444
Day or Night                 0.333333
Attendance               32364.111111
Game Length (minutes)      167.222222
Visitor Homeruns             1.222222
Visitor Pitchers Used        3.444444
Visitor Errors               0.888889
Home Homeruns                1.333333
Home Pitchers Used           3.555556
Home Errors                  0.666667
dtype: float64

Visitor Score                4.1250
Home Score                   5.1250
Game Length (outs)          52.2500
Day or Night                 0.3125
Attendance               35087.3125
Game Length (minutes)      172.0000
Visitor Homeruns             0.6875
Visitor Pitchers Used        4.3750
Visitor Errors               0.8125
Home Homeruns                0.9375
Home Pitchers Used           4.2500
Home Errors                  0.4375
dtype: float64

Visitor Score                4.428571
Home Score                   6.357143
Game Length (outs)          54.785714
Day or Night                 0.285714
Attendance               37957.642857
Game Length (minutes)      189.714286
Visitor Homeruns             1.071429
Visitor Pitchers Used        4.357143
Visitor Errors               1.000000
Home Homeruns                1.214286
Home Pitchers Used           4.000000
Home Errors                  0.857143
dtype: float64

Visitor Score                4.055556
Home Score                   5.444444
Game Length (outs)          52.611111
Day or Night                 0.277778
Attendance               33824.555556
Game Length (minutes)      180.611111
Visitor Homeruns             1.000000
Visitor Pitchers Used        3.777778
Visitor Errors               0.666667
Home Homeruns                1.388889
Home Pitchers Used           5.055556
Home Errors                  0.333333
dtype: float64

Visitor Score                2.0
Home Score                   9.0
Game Length (outs)          51.0
Day or Night                 1.0
Attendance               38098.0
Game Length (minutes)      179.0
Visitor Homeruns             1.0
Visitor Pitchers Used        6.0
Visitor Errors               0.0
Home Homeruns                1.0
Home Pitchers Used           2.0
Home Errors                  1.0
dtype: float64

Visitor Score                3.916667
Home Score                   6.250000
Game Length (outs)          55.750000
Day or Night                 0.500000
Attendance               28202.166667
Game Length (minutes)      187.166667
Visitor Homeruns             0.666667
Visitor Pitchers Used        3.916667
Visitor Errors               0.500000
Home Homeruns                1.250000
Home Pitchers Used           4.166667
Home Errors                  0.666667
dtype: float64

Visitor Score                4.250000
Home Score                   5.250000
Game Length (outs)          52.000000
Day or Night                 0.416667
Attendance               33088.666667
Game Length (minutes)      175.583333
Visitor Homeruns             0.750000
Visitor Pitchers Used        3.750000
Visitor Errors               0.666667
Home Homeruns                1.416667
Home Pitchers Used           4.250000
Home Errors                  0.250000
dtype: float64

Visitor Score                4.230769
Home Score                   4.769231
Game Length (outs)          52.000000
Day or Night                 0.230769
Attendance               35566.461538
Game Length (minutes)      175.307692
Visitor Homeruns             0.692308
Visitor Pitchers Used        3.846154
Visitor Errors               0.307692
Home Homeruns                0.846154
Home Pitchers Used           4.000000
Home Errors                  0.307692
dtype: float64

Visitor Score                5.133333
Home Score                   7.066667
Game Length (outs)          54.400000
Day or Night                 0.266667
Attendance               39615.666667
Game Length (minutes)      185.800000
Visitor Homeruns             1.266667
Visitor Pitchers Used        4.733333
Visitor Errors               0.666667
Home Homeruns                1.666667
Home Pitchers Used           4.200000
Home Errors                  0.533333
dtype: float64

Visitor Score                5.166667
Home Score                   5.666667
Game Length (outs)          52.416667
Day or Night                 0.416667
Attendance               39465.250000
Game Length (minutes)      184.916667
Visitor Homeruns             0.833333
Visitor Pitchers Used        4.000000
Visitor Errors               0.750000
Home Homeruns                1.416667
Home Pitchers Used           4.250000
Home Errors                  0.250000
dtype: float64

Visitor Score                5.117647
Home Score                   6.176471
Game Length (outs)          52.941176
Day or Night                 0.352941
Attendance               35857.235294
Game Length (minutes)      183.176471
Visitor Homeruns             1.411765
Visitor Pitchers Used        4.529412
Visitor Errors               0.705882
Home Homeruns                1.352941
Home Pitchers Used           4.882353
Home Errors                  0.764706
dtype: float64

Day of Week             NaN
Visitor                 NaN
Home                    NaN
Home Division           NaN
Visitor Score           NaN
Home Score              NaN
Game Length (outs)      NaN
Day or Night            NaN
Attendance              NaN
Game Length (minutes)   NaN
Visitor Homeruns        NaN
Visitor Pitchers Used   NaN
Visitor Errors          NaN
Home Homeruns           NaN
Home Pitchers Used      NaN
Home Errors             NaN
Month                   NaN
dtype: float64

Visitor Score                3.833333
Home Score                   4.500000
Game Length (outs)          53.250000
Day or Night                 0.333333
Attendance               33913.083333
Game Length (minutes)      177.833333
Visitor Homeruns             1.166667
Visitor Pitchers Used        3.833333
Visitor Errors               0.583333
Home Homeruns                0.833333
Home Pitchers Used           3.750000
Home Errors                  0.250000
dtype: float64

Visitor Score                5.5000
Home Score                   5.3750
Game Length (outs)          52.8750
Day or Night                 0.4375
Attendance               32810.1250
Game Length (minutes)      174.5000
Visitor Homeruns             0.8750
Visitor Pitchers Used        4.0000
Visitor Errors               0.6875
Home Homeruns                1.2500
Home Pitchers Used           4.2500
Home Errors                  0.5000
dtype: float64

Visitor Score                5.538462
Home Score                   5.461538
Game Length (outs)          54.846154
Day or Night                 0.307692
Attendance               37064.230769
Game Length (minutes)      192.307692
Visitor Homeruns             0.923077
Visitor Pitchers Used        4.076923
Visitor Errors               0.692308
Home Homeruns                1.076923
Home Pitchers Used           4.538462
Home Errors                  1.000000
dtype: float64

Visitor Score                5.272727
Home Score                   7.000000
Game Length (outs)          52.545455
Day or Night                 0.272727
Attendance               40535.181818
Game Length (minutes)      185.818182
Visitor Homeruns             1.363636
Visitor Pitchers Used        4.090909
Visitor Errors               0.727273
Home Homeruns                1.090909
Home Pitchers Used           4.181818
Home Errors                  0.818182
dtype: float64

Visitor Score                5.2500
Home Score                   6.0625
Game Length (outs)          54.8750
Day or Night                 0.3125
Attendance               37297.3750
Game Length (minutes)      192.0000
Visitor Homeruns             1.4375
Visitor Pitchers Used        4.1875
Visitor Errors               0.6875
Home Homeruns                1.3125
Home Pitchers Used           4.3125
Home Errors                  0.4375
dtype: float64

Visitor Score                6.076923
Home Score                   4.153846
Game Length (outs)          53.307692
Day or Night                 0.384615
Attendance               34875.230769
Game Length (minutes)      180.307692
Visitor Homeruns             1.769231
Visitor Pitchers Used        4.307692
Visitor Errors               0.538462
Home Homeruns                1.307692
Home Pitchers Used           4.923077
Home Errors                  1.230769
dtype: float64

Day of Week             NaN
Visitor                 NaN
Home                    NaN
Home Division           NaN
Visitor Score           NaN
Home Score              NaN
Game Length (outs)      NaN
Day or Night            NaN
Attendance              NaN
Game Length (minutes)   NaN
Visitor Homeruns        NaN
Visitor Pitchers Used   NaN
Visitor Errors          NaN
Home Homeruns           NaN
Home Pitchers Used      NaN
Home Errors             NaN
Month                   NaN
dtype: float64

Visitor Score                5.769231
Home Score                   6.461538
Game Length (outs)          53.461538
Day or Night                 0.307692
Attendance               30737.000000
Game Length (minutes)      195.000000
Visitor Homeruns             1.076923
Visitor Pitchers Used        4.230769
Visitor Errors               1.153846
Home Homeruns                1.153846
Home Pitchers Used           4.461538
Home Errors                  1.000000
dtype: float64

Visitor Score                6.714286
Home Score                   6.642857
Game Length (outs)          54.142857
Day or Night                 0.428571
Attendance               33698.357143
Game Length (minutes)      191.428571
Visitor Homeruns             1.500000
Visitor Pitchers Used        4.428571
Visitor Errors               0.642857
Home Homeruns                1.785714
Home Pitchers Used           4.500000
Home Errors                  0.785714
dtype: float64

Visitor Score                7.333333
Home Score                   5.800000
Game Length (outs)          53.933333
Day or Night                 0.400000
Attendance               37414.666667
Game Length (minutes)      193.066667
Visitor Homeruns             2.133333
Visitor Pitchers Used        3.800000
Visitor Errors               1.133333
Home Homeruns                1.466667
Home Pitchers Used           4.666667
Home Errors                  0.800000
dtype: float64

Visitor Score                6.000000
Home Score                   3.636364
Game Length (outs)          53.636364
Day or Night                 0.363636
Attendance               34372.818182
Game Length (minutes)      177.727273
Visitor Homeruns             1.636364
Visitor Pitchers Used        3.727273
Visitor Errors               0.909091
Home Homeruns                0.545455
Home Pitchers Used           4.636364
Home Errors                  0.545455
dtype: float64

Visitor Score                6.2500
Home Score                   6.1875
Game Length (outs)          52.5625
Day or Night                 0.2500
Attendance               29221.3125
Game Length (minutes)      181.4375
Visitor Homeruns             1.2500
Visitor Pitchers Used        4.1875
Visitor Errors               0.5625
Home Homeruns                1.0000
Home Pitchers Used           4.5625
Home Errors                  1.0000
dtype: float64

Visitor Score                6.500000
Home Score                   6.916667
Game Length (outs)          51.250000
Day or Night                 0.250000
Attendance               29353.166667
Game Length (minutes)      191.416667
Visitor Homeruns             1.083333
Visitor Pitchers Used        5.000000
Visitor Errors               0.833333
Home Homeruns                1.333333
Home Pitchers Used           5.083333
Home Errors                  0.500000
dtype: float64

Day of Week             NaN
Visitor                 NaN
Home                    NaN
Home Division           NaN
Visitor Score           NaN
Home Score              NaN
Game Length (outs)      NaN
Day or Night            NaN
Attendance              NaN
Game Length (minutes)   NaN
Visitor Homeruns        NaN
Visitor Pitchers Used   NaN
Visitor Errors          NaN
Home Homeruns           NaN
Home Pitchers Used      NaN
Home Errors             NaN
Month                   NaN
dtype: float64

Visitor Score                4.083333
Home Score                   5.833333
Game Length (outs)          54.000000
Day or Night                 0.583333
Attendance               28647.833333
Game Length (minutes)      184.250000
Visitor Homeruns             0.833333
Visitor Pitchers Used        4.166667
Visitor Errors               0.750000
Home Homeruns                1.166667
Home Pitchers Used           3.750000
Home Errors                  0.666667
dtype: float64

Visitor Score                4.5625
Home Score                   4.6875
Game Length (outs)          53.8750
Day or Night                 0.2500
Attendance               34977.6875
Game Length (minutes)      186.6250
Visitor Homeruns             0.5000
Visitor Pitchers Used        3.8125
Visitor Errors               1.1875
Home Homeruns                1.2500
Home Pitchers Used           3.9375
Home Errors                  0.5625
dtype: float64

Visitor Score                4.5000
Home Score                   5.2500
Game Length (outs)          54.5625
Day or Night                 0.5625
Attendance               36497.4375
Game Length (minutes)      188.6250
Visitor Homeruns             0.8750
Visitor Pitchers Used        4.2500
Visitor Errors               0.9375
Home Homeruns                1.2500
Home Pitchers Used           4.2500
Home Errors                  0.5000
dtype: float64

Visitor Score                4.615385
Home Score                   4.461538
Game Length (outs)          52.615385
Day or Night                 0.230769
Attendance               38594.692308
Game Length (minutes)      177.153846
Visitor Homeruns             1.461538
Visitor Pitchers Used        3.615385
Visitor Errors               0.923077
Home Homeruns                0.923077
Home Pitchers Used           4.076923
Home Errors                  0.461538
dtype: float64

Visitor Score                3.818182
Home Score                   6.181818
Game Length (outs)          51.818182
Day or Night                 0.181818
Attendance               33231.272727
Game Length (minutes)      176.454545
Visitor Homeruns             0.818182
Visitor Pitchers Used        3.454545
Visitor Errors               1.181818
Home Homeruns                0.636364
Home Pitchers Used           3.818182
Home Errors                  0.545455
dtype: float64

Visitor Score                7.000000
Home Score                   6.076923
Game Length (outs)          55.461538
Day or Night                 0.307692
Attendance               33782.846154
Game Length (minutes)      204.538462
Visitor Homeruns             0.846154
Visitor Pitchers Used        5.384615
Visitor Errors               0.538462
Home Homeruns                1.153846
Home Pitchers Used           5.615385
Home Errors                  0.692308
dtype: float64

Day of Week             NaN
Visitor                 NaN
Home                    NaN
Home Division           NaN
Visitor Score           NaN
Home Score              NaN
Game Length (outs)      NaN
Day or Night            NaN
Attendance              NaN
Game Length (minutes)   NaN
Visitor Homeruns        NaN
Visitor Pitchers Used   NaN
Visitor Errors          NaN
Home Homeruns           NaN
Home Pitchers Used      NaN
Home Errors             NaN
Month                   NaN
dtype: float64

Visitor Score                4.833333
Home Score                   7.416667
Game Length (outs)          53.000000
Day or Night                 0.416667
Attendance               30923.750000
Game Length (minutes)      188.750000
Visitor Homeruns             1.500000
Visitor Pitchers Used        3.833333
Visitor Errors               0.500000
Home Homeruns                1.833333
Home Pitchers Used           4.250000
Home Errors                  0.833333
dtype: float64

Visitor Score                4.416667
Home Score                   6.083333
Game Length (outs)          52.916667
Day or Night                 0.250000
Attendance               34658.000000
Game Length (minutes)      196.166667
Visitor Homeruns             1.000000
Visitor Pitchers Used        4.583333
Visitor Errors               0.833333
Home Homeruns                1.333333
Home Pitchers Used           4.333333
Home Errors                  0.416667
dtype: float64

Visitor Score                7.5000
Home Score                   5.5625
Game Length (outs)          52.4375
Day or Night                 0.3750
Attendance               33861.6250
Game Length (minutes)      196.9375
Visitor Homeruns             1.4375
Visitor Pitchers Used        4.3750
Visitor Errors               0.5000
Home Homeruns                1.1875
Home Pitchers Used           4.4375
Home Errors                  0.6875
dtype: float64

Visitor Score                5.5000
Home Score                   4.2500
Game Length (outs)          52.6875
Day or Night                 0.4375
Attendance               36046.2500
Game Length (minutes)      194.0625
Visitor Homeruns             0.8750
Visitor Pitchers Used        3.7500
Visitor Errors               0.3750
Home Homeruns                1.2500
Home Pitchers Used           4.5000
Home Errors                  0.6875
dtype: float64

Visitor Score                5.500000
Home Score                   6.250000
Game Length (outs)          55.916667
Day or Night                 0.250000
Attendance               33922.666667
Game Length (minutes)      198.416667
Visitor Homeruns             1.000000
Visitor Pitchers Used        4.000000
Visitor Errors               0.500000
Home Homeruns                1.583333
Home Pitchers Used           5.083333
Home Errors                  0.416667
dtype: float64

Visitor Score                4.538462
Home Score                   8.153846
Game Length (outs)          53.230769
Day or Night                 0.461538
Attendance               28288.461538
Game Length (minutes)      191.538462
Visitor Homeruns             0.846154
Visitor Pitchers Used        5.076923
Visitor Errors               0.769231
Home Homeruns                1.769231
Home Pitchers Used           4.923077
Home Errors                  0.307692
dtype: float64

Day of Week             NaN
Visitor                 NaN
Home                    NaN
Home Division           NaN
Visitor Score           NaN
Home Score              NaN
Game Length (outs)      NaN
Day or Night            NaN
Attendance              NaN
Game Length (minutes)   NaN
Visitor Homeruns        NaN
Visitor Pitchers Used   NaN
Visitor Errors          NaN
Home Homeruns           NaN
Home Pitchers Used      NaN
Home Errors             NaN
Month                   NaN
dtype: float64

Visitor Score                5.666667
Home Score                   4.555556
Game Length (outs)          54.111111
Day or Night                 0.333333
Attendance               33552.444444
Game Length (minutes)      186.111111
Visitor Homeruns             1.222222
Visitor Pitchers Used        4.222222
Visitor Errors               0.333333
Home Homeruns                1.000000
Home Pitchers Used           4.888889
Home Errors                  0.777778
dtype: float64

Visitor Score                5.916667
Home Score                   5.333333
Game Length (outs)          51.083333
Day or Night                 0.416667
Attendance               25626.083333
Game Length (minutes)      178.416667
Visitor Homeruns             0.666667
Visitor Pitchers Used        3.666667
Visitor Errors               0.750000
Home Homeruns                0.916667
Home Pitchers Used           4.166667
Home Errors                  0.666667
dtype: float64

Visitor Score                5.555556
Home Score                   5.944444
Game Length (outs)          52.888889
Day or Night                 0.444444
Attendance               31370.388889
Game Length (minutes)      188.277778
Visitor Homeruns             1.666667
Visitor Pitchers Used        4.111111
Visitor Errors               0.500000
Home Homeruns                1.388889
Home Pitchers Used           4.555556
Home Errors                  0.444444
dtype: float64

Visitor Score                5.583333
Home Score                   5.750000
Game Length (outs)          52.583333
Day or Night                 0.333333
Attendance               37045.333333
Game Length (minutes)      191.250000
Visitor Homeruns             1.250000
Visitor Pitchers Used        4.333333
Visitor Errors               0.416667
Home Homeruns                1.333333
Home Pitchers Used           5.000000
Home Errors                  0.583333
dtype: float64

Visitor Score                7.461538
Home Score                   5.153846
Game Length (outs)          54.307692
Day or Night                 0.230769
Attendance               31083.538462
Game Length (minutes)      195.615385
Visitor Homeruns             1.307692
Visitor Pitchers Used        4.538462
Visitor Errors               0.923077
Home Homeruns                1.230769
Home Pitchers Used           4.692308
Home Errors                  0.461538
dtype: float64

Visitor Score                5.705882
Home Score                   5.941176
Game Length (outs)          52.588235
Day or Night                 0.294118
Attendance               28471.000000
Game Length (minutes)      191.294118
Visitor Homeruns             1.117647
Visitor Pitchers Used        4.764706
Visitor Errors               0.823529
Home Homeruns                1.470588
Home Pitchers Used           5.529412
Home Errors                  0.705882
dtype: float64

Day of Week             NaN
Visitor                 NaN
Home                    NaN
Home Division           NaN
Visitor Score           NaN
Home Score              NaN
Game Length (outs)      NaN
Day or Night            NaN
Attendance              NaN
Game Length (minutes)   NaN
Visitor Homeruns        NaN
Visitor Pitchers Used   NaN
Visitor Errors          NaN
Home Homeruns           NaN
Home Pitchers Used      NaN
Home Errors             NaN
Month                   NaN
dtype: float64

Visitor Score                8.000000
Home Score                   5.750000
Game Length (outs)          54.500000
Day or Night                 0.333333
Attendance               29467.000000
Game Length (minutes)      205.083333
Visitor Homeruns             1.833333
Visitor Pitchers Used        4.333333
Visitor Errors               0.666667
Home Homeruns                1.416667
Home Pitchers Used           4.500000
Home Errors                  0.666667
dtype: float64

Visitor Score                6.000000
Home Score                   6.181818
Game Length (outs)          52.363636
Day or Night                 0.454545
Attendance               32345.272727
Game Length (minutes)      187.909091
Visitor Homeruns             1.363636
Visitor Pitchers Used        4.454545
Visitor Errors               0.545455
Home Homeruns                1.454545
Home Pitchers Used           4.090909
Home Errors                  0.636364
dtype: float64

Visitor Score                6.733333
Home Score                   6.933333
Game Length (outs)          52.533333
Day or Night                 0.466667
Attendance               33585.266667
Game Length (minutes)      196.800000
Visitor Homeruns             1.266667
Visitor Pitchers Used        4.066667
Visitor Errors               0.866667
Home Homeruns                1.466667
Home Pitchers Used           4.733333
Home Errors                  1.200000
dtype: float64

Visitor Score                5.181818
Home Score                   5.636364
Game Length (outs)          52.090909
Day or Night                 0.272727
Attendance               36928.909091
Game Length (minutes)      187.090909
Visitor Homeruns             0.727273
Visitor Pitchers Used        3.818182
Visitor Errors               0.454545
Home Homeruns                1.454545
Home Pitchers Used           4.454545
Home Errors                  0.636364
dtype: float64

Visitor Score                5.176471
Home Score                   6.823529
Game Length (outs)          53.176471
Day or Night                 0.294118
Attendance               32393.647059
Game Length (minutes)      197.294118
Visitor Homeruns             1.117647
Visitor Pitchers Used        4.588235
Visitor Errors               0.588235
Home Homeruns                1.352941
Home Pitchers Used           4.588235
Home Errors                  0.647059
dtype: float64

Visitor Score                4.538462
Home Score                   6.307692
Game Length (outs)          52.384615
Day or Night                 0.307692
Attendance               28602.769231
Game Length (minutes)      183.307692
Visitor Homeruns             1.000000
Visitor Pitchers Used        4.769231
Visitor Errors               0.538462
Home Homeruns                1.615385
Home Pitchers Used           3.615385
Home Errors                  0.461538
dtype: float64

Visitor Score                5.0
Home Score                   3.5
Game Length (outs)          60.0
Day or Night                 0.5
Attendance               30298.5
Game Length (minutes)      204.5
Visitor Homeruns             1.5
Visitor Pitchers Used        6.0
Visitor Errors               1.0
Home Homeruns                0.5
Home Pitchers Used           5.0
Home Errors                  0.5
dtype: float64

Visitor Score                6.153846
Home Score                   5.615385
Game Length (outs)          52.384615
Day or Night                 0.384615
Attendance               31039.076923
Game Length (minutes)      184.153846
Visitor Homeruns             1.230769
Visitor Pitchers Used        4.307692
Visitor Errors               0.692308
Home Homeruns                1.769231
Home Pitchers Used           4.153846
Home Errors                  0.692308
dtype: float64

Visitor Score                4.466667
Home Score                   5.266667
Game Length (outs)          52.400000
Day or Night                 0.400000
Attendance               38284.466667
Game Length (minutes)      180.733333
Visitor Homeruns             1.066667
Visitor Pitchers Used        3.800000
Visitor Errors               0.466667
Home Homeruns                1.000000
Home Pitchers Used           4.000000
Home Errors                  0.400000
dtype: float64

Visitor Score                6.222222
Home Score                   7.000000
Game Length (outs)          51.888889
Day or Night                 0.444444
Attendance               41865.222222
Game Length (minutes)      193.444444
Visitor Homeruns             1.777778
Visitor Pitchers Used        4.333333
Visitor Errors               0.888889
Home Homeruns                1.222222
Home Pitchers Used           4.333333
Home Errors                  0.333333
dtype: float64

Visitor Score                5.000000
Home Score                   7.769231
Game Length (outs)          51.923077
Day or Night                 0.307692
Attendance               40335.769231
Game Length (minutes)      193.307692
Visitor Homeruns             1.230769
Visitor Pitchers Used        4.000000
Visitor Errors               0.615385
Home Homeruns                1.846154
Home Pitchers Used           4.000000
Home Errors                  0.615385
dtype: float64

Visitor Score                4.7500
Home Score                   5.1875
Game Length (outs)          52.5625
Day or Night                 0.3125
Attendance               34902.3125
Game Length (minutes)      193.9375
Visitor Homeruns             1.3125
Visitor Pitchers Used        4.4375
Visitor Errors               0.1250
Home Homeruns                1.3125
Home Pitchers Used           4.2500
Home Errors                  0.3750
dtype: float64

Visitor Score                4.642857
Home Score                   6.142857
Game Length (outs)          52.642857
Day or Night                 0.285714
Attendance               34524.285714
Game Length (minutes)      196.642857
Visitor Homeruns             0.928571
Visitor Pitchers Used        5.571429
Visitor Errors               0.785714
Home Homeruns                1.142857
Home Pitchers Used           5.214286
Home Errors                  0.714286
dtype: float64

Visitor Score                6.0
Home Score                   3.0
Game Length (outs)          54.0
Day or Night                 1.0
Attendance               32946.0
Game Length (minutes)      219.0
Visitor Homeruns             0.0
Visitor Pitchers Used        6.0
Visitor Errors               0.0
Home Homeruns                0.0
Home Pitchers Used           6.0
Home Errors                  0.0
dtype: float64

Visitor Score                6.000000
Home Score                   4.583333
Game Length (outs)          53.416667
Day or Night                 0.416667
Attendance               33251.750000
Game Length (minutes)      182.083333
Visitor Homeruns             1.250000
Visitor Pitchers Used        4.250000
Visitor Errors               0.750000
Home Homeruns                1.083333
Home Pitchers Used           4.500000
Home Errors                  0.250000
dtype: float64

Visitor Score                5.083333
Home Score                   5.166667
Game Length (outs)          53.583333
Day or Night                 0.250000
Attendance               34292.250000
Game Length (minutes)      190.916667
Visitor Homeruns             1.333333
Visitor Pitchers Used        4.750000
Visitor Errors               0.750000
Home Homeruns                1.250000
Home Pitchers Used           4.416667
Home Errors                  0.166667
dtype: float64

Visitor Score                8.538462
Home Score                   6.076923
Game Length (outs)          53.076923
Day or Night                 0.384615
Attendance               38900.307692
Game Length (minutes)      194.153846
Visitor Homeruns             2.000000
Visitor Pitchers Used        4.692308
Visitor Errors               0.692308
Home Homeruns                1.461538
Home Pitchers Used           4.769231
Home Errors                  0.615385
dtype: float64

Visitor Score                2.571429
Home Score                   5.285714
Game Length (outs)          51.928571
Day or Night                 0.214286
Attendance               42214.285714
Game Length (minutes)      179.214286
Visitor Homeruns             0.642857
Visitor Pitchers Used        4.071429
Visitor Errors               0.428571
Home Homeruns                1.428571
Home Pitchers Used           3.857143
Home Errors                  0.428571
dtype: float64

Visitor Score                4.615385
Home Score                   4.153846
Game Length (outs)          52.846154
Day or Night                 0.307692
Attendance               38101.923077
Game Length (minutes)      179.153846
Visitor Homeruns             1.307692
Visitor Pitchers Used        3.769231
Visitor Errors               1.076923
Home Homeruns                0.923077
Home Pitchers Used           4.153846
Home Errors                  0.692308
dtype: float64

Visitor Score                3.764706
Home Score                   7.117647
Game Length (outs)          51.764706
Day or Night                 0.294118
Attendance               36077.823529
Game Length (minutes)      190.705882
Visitor Homeruns             1.058824
Visitor Pitchers Used        5.000000
Visitor Errors               0.411765
Home Homeruns                2.352941
Home Pitchers Used           4.823529
Home Errors                  0.588235
dtype: float64

Day of Week             NaN
Visitor                 NaN
Home                    NaN
Home Division           NaN
Visitor Score           NaN
Home Score              NaN
Game Length (outs)      NaN
Day or Night            NaN
Attendance              NaN
Game Length (minutes)   NaN
Visitor Homeruns        NaN
Visitor Pitchers Used   NaN
Visitor Errors          NaN
Home Homeruns           NaN
Home Pitchers Used      NaN
Home Errors             NaN
Month                   NaN
dtype: float64

In [24]:
COL['Game Length (minutes)'].mean()

187.3740740740741

In [25]:
COL.head()
W.head()

,Day of Week,Visitor,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,Attendance,Game Length (minutes),Visitor Homeruns,Visitor Pitchers Used,Visitor Errors,Home Homeruns,Home Pitchers Used,Home Errors,Month,Extra Innings
Date,,,,,,,,,,,,,,,,,,
2009-04-10,Fri,PHI,COL,NL,3,10,51,1.0,49427.0,154,1,4,0,1,3,1,2009-04-01,0
2009-04-11,Sat,PHI,COL,NL,8,4,54,0.0,35251.0,181,1,3,0,3,6,0,2009-04-01,0
2009-04-12,Sun,PHI,COL,NL,7,5,54,1.0,21628.0,196,2,6,0,1,5,0,2009-04-01,0
2009-04-24,Fri,LAN,COL,NL,6,5,54,0.0,36151.0,225,0,4,1,1,5,0,2009-04-01,0
2009-04-25,Sat,LAN,COL,NL,6,5,54,0.0,31476.0,181,0,2,0,1,5,0,2009-04-01,0

,ActHigh,ActLow,ActAvg,NormHigh,NormAvg.,NormDept,PrecipAmt,SnowAmt,Month
ObsDate,,,,,,,,,
2009-04-01,46,23,35,61,46,-11,0.17,0.7,2009-04-01
2009-04-02,55,19,37,61,46,-9,0.1,0.0,2009-04-01
2009-04-03,55,32,44,61,47,-3,0.3,0.4,2009-04-01
2009-04-04,32,19,26,61,47,-21,0.4,1.8,2009-04-01
2009-04-05,34,18,26,62,47,-21,0.04,0.4,2009-04-01

In [26]:
COL['deltaGame']= COL['Game Length (minutes)'] - (COL['Game Length (minutes)'].mean())

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [27]:
COL.head()

,Day of Week,Visitor,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,Attendance,Game Length (minutes),Visitor Homeruns,Visitor Pitchers Used,Visitor Errors,Home Homeruns,Home Pitchers Used,Home Errors,Month,Extra Innings,deltaGame
Date,,,,,,,,,,,,,,,,,,,
2009-04-10,Fri,PHI,COL,NL,3,10,51,1.0,49427.0,154,1,4,0,1,3,1,2009-04-01,0,-33.374074
2009-04-11,Sat,PHI,COL,NL,8,4,54,0.0,35251.0,181,1,3,0,3,6,0,2009-04-01,0,-6.374074
2009-04-12,Sun,PHI,COL,NL,7,5,54,1.0,21628.0,196,2,6,0,1,5,0,2009-04-01,0,8.625926
2009-04-24,Fri,LAN,COL,NL,6,5,54,0.0,36151.0,225,0,4,1,1,5,0,2009-04-01,0,37.625926
2009-04-25,Sat,LAN,COL,NL,6,5,54,0.0,31476.0,181,0,2,0,1,5,0,2009-04-01,0,-6.374074

In [28]:
COW.head()

,Day of Week,Visitor,Home,Home Division,Visitor Score,Home Score,Game Length (outs),Day or Night,Attendance,Game Length (minutes),...,Home Errors,Month,ActHigh,ActLow,ActAvg,NormHigh,NormAvg.,NormDept,PrecipAmt,SnowAmt
Date,,,,,,,,,,,,,,,,,,,,,
2009-04-10,Fri,PHI,COL,NL,3,10,51,1.0,49427.0,154,...,1,2009-04-01,59,27,43,63,48,-5,0,0.0
2009-04-11,Sat,PHI,COL,NL,8,4,54,0.0,35251.0,181,...,0,2009-04-01,57,36,47,63,48,-1,0,0.0
2009-04-12,Sun,PHI,COL,NL,7,5,54,1.0,21628.0,196,...,0,2009-04-01,46,37,42,63,48,-6,0,0.0
2009-04-24,Fri,LAN,COL,NL,6,5,54,0.0,36151.0,225,...,0,2009-04-01,66,37,52,66,52,0,0,0.0
2009-04-25,Sat,LAN,COL,NL,6,5,54,0.0,31476.0,181,...,0,2009-04-01,46,39,43,67,52,-9,0,0.0